In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("C:\\Users\Dee1\Downloads\churn-modellingcsv\Churn_Modelling.csv")
data

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [5]:
data.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
data.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [7]:
X = data.iloc[:, 3:13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
Y = data.iloc[:, 13].values
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [9]:
# encoding categorical data

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

oneHotEncoder = OneHotEncoder(categorical_features = [1])
X = oneHotEncoder.fit_transform(X).toarray()
X = X[:, 1:]


c:\users\dee1\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
c:\users\dee1\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [11]:
# splitting data set into train test split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.35, random_state = 0)
print("X_train set : ", X_train)
print("X_test set : ", X_test)
print("Y_train set : ", Y_train)
print("Y_test set : ", Y_test)

X_train set :  [[1.0000000e+00 0.0000000e+00 6.5100000e+02 ... 1.0000000e+00
  0.0000000e+00 6.6389430e+04]
 [0.0000000e+00 0.0000000e+00 4.8100000e+02 ... 1.0000000e+00
  0.0000000e+00 1.4521596e+05]
 [0.0000000e+00 1.0000000e+00 5.7600000e+02 ... 0.0000000e+00
  1.0000000e+00 3.4101060e+04]
 ...
 [0.0000000e+00 0.0000000e+00 7.3800000e+02 ... 1.0000000e+00
  0.0000000e+00 1.8142987e+05]
 [0.0000000e+00 1.0000000e+00 5.9000000e+02 ... 1.0000000e+00
  1.0000000e+00 1.4875016e+05]
 [1.0000000e+00 0.0000000e+00 6.2300000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1885526e+05]]
X_test set :  [[1.0000000e+00 0.0000000e+00 5.9700000e+02 ... 1.0000000e+00
  1.0000000e+00 1.9285267e+05]
 [0.0000000e+00 0.0000000e+00 5.2300000e+02 ... 1.0000000e+00
  0.0000000e+00 1.2870210e+05]
 [0.0000000e+00 1.0000000e+00 7.0600000e+02 ... 1.0000000e+00
  1.0000000e+00 7.5732250e+04]
 ...
 [0.0000000e+00 0.0000000e+00 7.2100000e+02 ... 1.0000000e+00
  1.0000000e+00 1.4487467e+05]
 [0.0000000e+00 0.0000000e+00 

In [12]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) 

In [14]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras import backend
from tensorflow.python.framework import ops
ops.reset_default_graph()

model = Sequential()

In [16]:
model.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim=11))
model.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
model.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

In [36]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [37]:
model.fit(X_train, Y_train, batch_size=10, epochs=100, validation_split=0.1)

Train on 5850 samples, validate on 650 samples
Epoch 1/100
5850/5850 [==============================] - 1s 140us/sample - loss: 0.3983 - accuracy: 0.8342 - val_loss: 0.3732 - val_accuracy: 0.8538
Epoch 2/100
5850/5850 [==============================] - 1s 114us/sample - loss: 0.3981 - accuracy: 0.8338 - val_loss: 0.3736 - val_accuracy: 0.8492
Epoch 3/100
5850/5850 [==============================] - 1s 193us/sample - loss: 0.3980 - accuracy: 0.8361 - val_loss: 0.3727 - val_accuracy: 0.8508
Epoch 4/100
5850/5850 [==============================] - 1s 167us/sample - loss: 0.3984 - accuracy: 0.8342 - val_loss: 0.3725 - val_accuracy: 0.8538
Epoch 5/100
5850/5850 [==============================] - 0s 82us/sample - loss: 0.3983 - accuracy: 0.8354 - val_loss: 0.3743 - val_accuracy: 0.8508
Epoch 6/100
5850/5850 [==============================] - 0s 82us/sample - loss: 0.3975 - accuracy: 0.8349 - val_loss: 0.3719 - val_accuracy: 0.8477
Epoch 7/100
5850/5850 [==============================] - 0s 8

5850/5850 [==============================] - 1s 130us/sample - loss: 0.3970 - accuracy: 0.8354 - val_loss: 0.3767 - val_accuracy: 0.8508
Epoch 56/100
5850/5850 [==============================] - 1s 125us/sample - loss: 0.3979 - accuracy: 0.8361 - val_loss: 0.3733 - val_accuracy: 0.8554
Epoch 57/100
5850/5850 [==============================] - 1s 123us/sample - loss: 0.3968 - accuracy: 0.8366 - val_loss: 0.3755 - val_accuracy: 0.8585
Epoch 58/100
5850/5850 [==============================] - 1s 126us/sample - loss: 0.3973 - accuracy: 0.8369 - val_loss: 0.3764 - val_accuracy: 0.8600
Epoch 59/100
5850/5850 [==============================] - 1s 139us/sample - loss: 0.3969 - accuracy: 0.8356 - val_loss: 0.3738 - val_accuracy: 0.8523
Epoch 60/100
5850/5850 [==============================] - 1s 118us/sample - loss: 0.3974 - accuracy: 0.8362 - val_loss: 0.3740 - val_accuracy: 0.8600
Epoch 61/100
5850/5850 [==============================] - 1s 123us/sample - loss: 0.3973 - accuracy: 0.8374 - val

In [38]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

In [39]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
print(cm)
backend.clear_session()

[[2699   80]
 [ 460  261]]
